name: weather_elt    # Same with project name in profiles.yml
version: 1.0.0
config-version: 2
profile: weather_elt # Same with project name in profiles.yml

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]

models:
  weather_elt:   # Same with project name in profiles.yml
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table

